// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyDCyL9ebsOGG5ZvwcRCENFArB4sMLehRmw',
    appId: '1:603463850939:android:7e2fc0e28ecdc4d523c29e',
    messagingSenderId: '603463850939',
    projectId: 'mobil-bb580',
    storageBucket: 'mobil-bb580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm82eHhvxFyTo9ID_5teWv68QB1rCIUSA',
    appId: '1:603463850939:ios:efe39c3269a8331223c29e',
    messagingSenderId: '603463850939',
    projectId: 'mobil-bb580',
    storageBucket: 'mobil-bb580.appspot.com',
=======
    apiKey: 'AIzaSyD5cHkb21Tt0QXmLLjOwE9shpqCH6cxG-M',
    appId: '1:705396185578:android:3cd17cafd34327a3a43a93',
    messagingSenderId: '705396185578',
    projectId: 'mybike-192d6',
    storageBucket: 'mybike-192d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVM0eu06UE1GA4KnbXtxQy6qnCfE-b0aI',
    appId: '1:705396185578:ios:02eb5406ecd9f0d4a43a93',
    messagingSenderId: '705396185578',
    projectId: 'mybike-192d6',
    storageBucket: 'mybike-192d6.appspot.com',
>>>>>>> d0d9ce20a90137ce6f85275a319740c73e17cb52
    iosBundleId: 'com.valentin.bike.myBike',
  );
}
